import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Footer from "./components/Footer";
import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Performance Marketing Expert in UAE | Meta, Google, LinkedIn, TikTok Ads | Lena Bara",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css"
        />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Google Tag Manager (gtag.js) */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=AW-17042420719"
          strategy="afterInteractive"
        />
        <Script id="google-ads-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'AW-17042420719');
          `}
        </Script>
        <Script
          id="marketing-loaders"
          strategy="afterInteractive"
        >{`
          window.__enableMarketingScripts = window.__enableMarketingScripts || function () {
            if (window.__marketingScriptsLoaded) return;
            window.__marketingScriptsLoaded = true;

            // GA4
            (function loadGA4() {
              var measurementId = "G-CBSDXPH5VB";
              if (!measurementId) return;
              if (!window.dataLayer) window.dataLayer = [];
              function gtag(){ window.dataLayer.push(arguments); }
              window.gtag = window.gtag || gtag;
              gtag("js", new Date());
              gtag("config", measurementId);
              var ga = document.createElement("script");
              ga.async = true;
              ga.src = "https://www.googletagmanager.com/gtag/js?id=" + measurementId;
              document.head.appendChild(ga);
            })();

            // Meta Pixel
            (function loadMetaPixel() {
              if (window.fbq) return;
              var n = window.fbq = function(){ n.callMethod ? n.callMethod.apply(n, arguments) : n.queue.push(arguments); };
              if (!window._fbq) window._fbq = n;
              n.push = n;
              n.loaded = !0;
              n.version = "2.0";
              n.queue = [];
              var t = document.createElement("script");
              t.async = !0;
              t.src = "https://connect.facebook.net/en_US/fbevents.js";
              document.head.appendChild(t);
              n("init", "1217425950383428");
              n("track", "PageView");
            })();

            // Placeholder for Google Ads / Search Ads remarketing
            window.__initGoogleAds = window.__initGoogleAds || function () {
              console.warn("Google Search Ads snippet is not configured yet.");
            };
          };
        `}</Script>
        <Script
          src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js"
          strategy="afterInteractive"
        />
        <Script id="cookieconsent-init" strategy="afterInteractive">{`
          window.addEventListener("load", function(){
            try {
              if (window.cookieconsent && typeof window.cookieconsent.initialise === 'function') {
                window.cookieconsent.initialise({
                  type: "opt-in",
                  palette: {
                    popup: { background: "#1C1B17" },
                    button: { background: "#EB4604" }
                  },
                  content: {
                    message: "We use cookies to improve your experience. By continuing, you agree to our cookie policy.",
                    dismiss: "Accept",
                    link: "Learn more",
                    href: "/privacy-policy"
                  },
                  onInitialise: function (status) {
                    if (this.hasConsented() && window.__enableMarketingScripts) {
                      window.__enableMarketingScripts();
                    }
                  },
                  onStatusChange: function (status) {
                    if (this.hasConsented() && window.__enableMarketingScripts) {
                      window.__enableMarketingScripts();
                    }
                  }
                });
              }
            } catch {}
          });
        `}</Script>
        {/* PostHog analytics bootstrap (uses NEXT_PUBLIC_POSTHOG_KEY/HOST) */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
  !function(t,e){var o,n,p,r;e.__SV||(window.posthog=e,e._i=[],e.init=function(i,s,a){function g(t,e){var o=e.split(".");2==o.length&&(t=t[o[0]],e=o[1]),t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}}(p=t.createElement("script")).type="text/javascript",p.async=!0,p.src=s.api_host+"/static/array.js",(r=t.getElementsByTagName("script")[0]).parentNode.insertBefore(p,r);var u=e;void 0!==a?u=e[a]=[]:a="posthog",u.people=u.people||[],u.toString=function(t){var e="posthog";return"posthog"!==a&&(e+="."+a),t||(e+=" (stub)"),e},u.people.toString=function(){return u.toString(1)+".people (stub)"};var c="capture identify alias people.set people.set_once set_config register register_once unregister opt_out_capturing has_opted_out_capturing opt_in_capturing reset isFeatureEnabled onFeatureFlags loadFeatureFlags group updateEarlyAccessFeatureEnrollment getEarlyAccessFeatures getActiveMatchingSurveys getOnceFlags getSessionId".split(" ");for(n=0;n<c.length;n++)g(u,c[n]);e._i.push([i,s,a])},e.__SV=1)}(document,window.posthog||[]);
  (function(){
    var key = '${process.env.NEXT_PUBLIC_POSTHOG_KEY || ''}';
    var host = '${process.env.NEXT_PUBLIC_POSTHOG_HOST || 'https://app.posthog.com'}';
    if(!key) return; // no init without key
    posthog.init(key, { api_host: host, capture_pageview: true, autocapture: true });

    // UTM + page context capture on first load
    try {
      var url = new URL(window.location.href);
      var params = url.searchParams;
      var utm = {
        utm_source: params.get('utm_source') || undefined,
        utm_medium: params.get('utm_medium') || undefined,
        utm_campaign: params.get('utm_campaign') || undefined,
        utm_content: params.get('utm_content') || undefined,
        utm_term: params.get('utm_term') || undefined,
        referrer: document.referrer || undefined,
        initial_path: location.pathname,
        initial_title: document.title
      };
      // Persist on first visit if not already present
      var stored = {};
      try { stored = JSON.parse(localStorage.getItem('lenabara_utm') || '{}'); } catch {}
      if (!stored.initial_path) {
        localStorage.setItem('lenabara_utm', JSON.stringify(utm));
        try { posthog.capture('utm_captured', utm); } catch {}
      }
      // Register super properties for all subsequent events
      try {
        var merged = Object.assign({}, stored.initial_path ? stored : utm);
        posthog.register(merged);
        posthog.capture('page_init', { path: location.pathname, title: document.title });
      } catch {}
    } catch {}
  
  })();
            `,
          }}
        />
        <Header />
        {children}
        <Footer />
        {/* Lightweight analytics for elements with data-track */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(() => {
  function post(event, props) {
    try {
      const payload = { event, props, ts: Date.now() };
      const blob = new Blob([JSON.stringify(payload)], { type: 'application/json' });
      if (navigator.sendBeacon) {
        navigator.sendBeacon('/api/events', blob);
      } else {
        fetch('/api/events', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload), keepalive: true }).catch(()=>{});
      }
    } catch {}
  }
  addEventListener('click', (e) => {
    const el = e.target instanceof Element ? e.target.closest('[data-track]') : null;
    if (el) {
      const event = el.getAttribute('data-track') || 'click';
      let props = { href: el.getAttribute('href') || undefined };
      try {
        const utm = JSON.parse(localStorage.getItem('lenabara_utm') || '{}') || {};
        if (utm && utm.utm_source) props = { ...props, first_utm_source: utm.utm_source };
        const calc = JSON.parse(localStorage.getItem('lenabara_calc') || '{}') || {};
        if (calc && calc.plan) props = { ...props, plan: calc.plan };
      } catch {}
      post(event, props);
      try { if (window.posthog && typeof window.posthog.capture === 'function') window.posthog.capture(event, props); } catch {}
    }
  }, { capture: true });
})();`,
          }}
        />
      </body>
    </html>
  );
}
